; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24213.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\myald\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
